# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: X-Cart 5 REST API Reference
email: daemos@x-cart.com
description: X-Cart REST API Reference and Documentation
baseurl: "/rest-api" # the subpath of your site, e.g. /blog
url: "http://devs.x-cart.com" # the base hostname & protocol for your site
encoding: utf-8
repository: xcart/xc5-restapi
ga_code: 

# Build settings
safe: false
markdown: kramdown
incremental: false
lsi: true

kramdown:
  input: GFM

gems:
  - jekyll-redirect-from
  - jekyll-xcart-plugins

navigation_starting_level: 2

# APIs

swagger_pages:
    latest_api: 5.3.3.3
    path: "/api/v:version/"

swagger:
  - id: 5_3_3_0
    json: 'spec/5.3.3.0.json'
  - id: 5_3_3_3
    json: 'spec/5.3.3.3.json'

# Languages

lang_default: en
lang:
    en: English
    ru: Russian

# Sort orders

sort_default: order

header_container:
  default: "container"
  api_index: "reference container"
  article: "text container"
  article_with_sidebar: "container"
  page: "text container"
  reference: "reference container"
  wide_page: "widepage container"

# Category-wide Page ranking

# category_pr:
#     changelog: 0.2